### ISSUE TITLE
space and time taken up

### ISSUE THREAD

**Issue by chandkc** [chandkc/HTVS#10]
@sanvidat @chandkc

**Comment by chandkc** [comment]
Estimate the space for one comb. from existing run. @sanvidat

**Comment by chandkc** [comment]
GA RUN=2
Protein: 4600 atoms
LIG: 20  atoms
==> 1 MB

Our factor 1.2 MB

2 minutes for each comb (on an average)
For 2 comb in Q, time taken=2*2=4 minutes
Total time=4+max(1, 5%)=5 minutes

**Comment by chandkc** [comment]
2 GA runs --> 3.5 minutes
1 CG rauns --> 1.75 minutes

**Comment by sanvidat** [comment]
Space estimation for the server side and time estimation for job completion is implemented.
