### ISSUE TITLE
PIPL03- v2_test- Software crashing

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/HTVS#18]
Machine PIPL03, Software ubuntu version- v2_test, HTVS getting crashed on clicking 'Next' for docking after target and ligand selection.
![terminal error3](https://user-images.githubusercontent.com/111036161/184839285-d9d592ac-bfa0-4da4-b1ce-1e354f3a2f39.JPG)

**Comment by sanvidat** [comment]
Possible reason Nvidia-Driver currupted.
Source of this error is NGL viewer (QtWebEngine).

**Comment by chandkc** [comment]
@prescienceit 
Info message to the User, the graphics driver is not working as intended.

**Comment by chandkc** [comment]
Unable to reproduce the above error/issue.
@prescienceit will try to reproduce the issue, if at all, by turning off the NVIDIA-driver.
