### ISSUE TITLE
PIPL01- HTVS- Data analysis & Download page non responsive

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/HTVS#19]
**PIPL01- windows version- PRiNS_v2.exe- App- HTVS**
The graphs are not updating on selection of different data types. 'Refresh', 'Next', 'Back' not working on these two pages right now. Download options also non-responsive. Repeated 3 times. Software launched by clicking on it, so no powershell data was available in the case.
![image (1)](https://user-images.githubusercontent.com/111036161/185065076-2665c591-3bc4-4b91-8548-fe57d88695a4.png)
![image](https://user-images.githubusercontent.com/111036161/185065085-ee22cea0-797e-4efc-a7d5-49d771f610aa.png)

**Comment by sanvidat** [comment]
Now data analysis and download page are responsive.
