### ISSUE TITLE
VDI-HTVS-Software Crashing

### ISSUE THREAD

**Issue by sanvidat** [chandkc/HTVS#20]
![Screenshot from 2022-08-16 13-46-48](https://user-images.githubusercontent.com/105784499/185358135-3fcad93c-5ac0-4873-a07a-d8bba3159c4f.png)

**Comment by sanvidat** [comment]
Bug is fixed.
Source of this error is conda environment is not activated and some check and balances are not implemented.

**Comment by chandkc** [comment]
@prescienceit 
Please check.  
If we are using 'biopandas', is it within the conda env, or outside?

**Comment by sanvidat** [comment]
@chandkc 
Biopandas is inside the conda env
![biopandas](https://user-images.githubusercontent.com/105784499/185843938-15534a94-6e49-4c7e-86fb-ea48731416f7.png)

**Comment by mdaakhan** [comment]
we can take out bio pandas outside the conda env,
pip install biopandas
@sanvidat please use this to install outside the conda env will update the docker image with this package
try to avoid cond env in HTVS

**Comment by chandkc** [comment]
1. Install python3 outside conda
