### ISSUE TITLE
HTVS Enhancement Suggestion 1

### ISSUE THREAD

**Issue by mdaakhan** [chandkc/HTVS#22]
1. Smiles column can be removed after selecting the smiles (ID Selection)
2. Run Docking Button should be disabled till the target and Resource is not selected
3. After Submitting the Jobs before the result (Server and Target Button Should Be Disabled (Should be Replaced with Tab Widgit)
4. TOP Docking Tab widget should be hidden 
5. Pychart Pop up is appearing on each button click or refresh

**Comment by chandkc** [comment]
2 - 5 needs to be fixed.

**Comment by sanvidat** [comment]
1. 1 done- V2.0.0.0.3
2.  4 done - V2.0.0.0.2
3. 2 done - V2.0.0.0.4
