### ISSUE TITLE
Refresh Button

### ISSUE THREAD

**Issue by mdaakhan** [chandkc/HTVS#23]
1. Refresh Button on Docking Grid and Data Analysis part should update both (Plots and Current Status of the Jobs)
2. The resume button can be hidden after jobs got completed 
3. in Exported file Heading Host can be changed 
4. Disabling of Remote and Complex button 
5. Extract the Download data 
6. If positive energy is not available can we disable that button

**Comment by chandkc** [comment]
3. Use 'Resource' in the header

2-6 attend

**Comment by sanvidat** [comment]
2-6 is done -V2.0.0.0.2
