### ISSUE TITLE
Complex Based on (Download Section)

### ISSUE THREAD

**Issue by mdaakhan** [chandkc/HTVS#24]
Can we change the description not clear to me?

The download section is not working for Complex Based on (Binding Energy and Score, Hydrogen Bond) also Processing icon is displaying 

![Screenshot 2022-08-18 171447](https://user-images.githubusercontent.com/69871502/185386930-b682826a-4ccd-427f-b089-eecf32e2a15d.png)

**Comment by sanvidat** [comment]
1. The download button is working now and messages that come in the terminal for QmessageBox are gone.
2. Please suggest some name for the button(Complex Based ON) for better clarity.
