### ISSUE TITLE
On Wrong Input file in HTVS - SW crashes

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/HTVS#25]
Hi,

I had given wrong input file (smi file with headers), sw had given information message saying SMI file is wrong. But after that sw got crashed.

**Comment by sanvidat** [comment]
![pop-up](https://user-images.githubusercontent.com/105784499/186143163-480c02f3-b913-4f41-8a93-c5bbcd4abfeb.png)
Source of this error is pop up inside the thread.
bug fixed.

**Comment by sanvidat** [comment]
Update - 1. Input file is not in correct format.
               2. Required format.

**Comment by sanvidat** [comment]
Updated
