### ISSUE TITLE
Clear jobs 

### ISSUE THREAD

**Issue by sanvidat** [chandkc/HTVS#27]
1. Clear UI data (Job status page)

**Comment by chandkc** [comment]
1. Terminate and Clear
2. a. Kill the submitted script
    b. Kill the running jobs
    c. remove server data
    
    d. Initialize the pie chart and table + state saved data
    e. Plots/graphs reinitialize + state save data

**Comment by chandkc** [comment]
Terminate and Clear
Alert
-----
It will permanently delete the data from the server and clear the local data. 
Do you want to continue?

**Comment by sanvidat** [comment]
fixed
