### ISSUE TITLE
Clear Jobs: Jobs were stuck in steps excluded autodock and autogrid how to terminate that job.

### ISSUE THREAD

**Issue by sanvidat** [chandkc/HTVS#28]

**Comment by SumedhaBhosale** [comment]
Hi,

Adding screenshot of terminal after clicking "clear job" 

![HTVS_ClearJob](https://user-images.githubusercontent.com/105902516/186353657-a0823b3b-708b-44bd-aa15-dc642df46f6e.png)

**Comment by sanvidat** [comment]
1. Jobs are not clearing at server side.
3. Distinguish clear and terminate.

**Comment by sanvidat** [comment]
fixed.
