### ISSUE TITLE
HTVS- plot labels - not in tilted position after plot background colour change

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/HTVS#29]
Hi,

Check plot labels in Light backgrounds. Some problem with positioning. 

![HTVS_PlotLabels](https://user-images.githubusercontent.com/105902516/186359502-6e04225a-c05f-47eb-8674-043f10cdd1e7.png)

**Comment by chandkc** [comment]
Tilt the x-axis label to 45 degrees.
