### ISSUE TITLE
Download - Remote Directory - Pop-up message 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/HTVS#30]
Hi,

If user is trying to download remote directory, one pop-up message comes and estimated directory size is updated in that message. This size is usually Job ids from different servers user has used. 
 I had 4 servers, so this pop-up message got updated 4 times. Now for saying No - we have to click it multiple times in my case 4 times. 

Can we just put one message with all size added together ? It would be great in case of large number of servers.

**Comment by SumedhaBhosale** [comment]
![RemoteDir3](https://user-images.githubusercontent.com/105902516/186564070-7ede0b60-21d6-4af2-94e3-6f55083e0849.png)

![RemoteDir2](https://user-images.githubusercontent.com/105902516/186564091-e3ed5de1-21f6-4c68-910e-990b6837982f.png)

![RemoteDir1](https://user-images.githubusercontent.com/105902516/186564115-a1a2c9b5-2726-480e-9a2f-8a60018db758.png)

![RemoteDir_4](https://user-images.githubusercontent.com/105902516/186564131-49c5f91d-36a1-401a-b731-357023ae90fb.png)

**Comment by SumedhaBhosale** [comment]
In fact, when Remote Directory download is complete, after that this pop-up message (seen in above screenshot) stays idle. It should go away. Please check !

**Comment by sanvidat** [comment]
bug fixed testing is remaining.

**Comment by sanvidat** [comment]
fixed
