### ISSUE TITLE
Errors in Error.csv - Lowest energy conformation (pdbqt) not found

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/HTVS#31]
Hi,

please check if we can throw this error from sw. 

Linux OS
Exe shared on 10Aug 

![HTVS_error](https://user-images.githubusercontent.com/105902516/186605270-af9e3c97-0096-4b43-99f0-fd439634e585.png)

**Comment by SumedhaBhosale** [comment]
Checked few of .dlg file from results. Docking was unsuccessful because of too many torsions in ligand. 
Autodock doesn't allow torsions more than 32 for ligand molecules. May be we should put this as error instead of pdbqt not found. 
At the bottom of every .dlg file - successful/unsuccessful completion of docking is written. Can we extract that statement and put as error ? 


_Attaching Screenhost_
![HTVS_Torsions](https://user-images.githubusercontent.com/105902516/188113733-a28f55bf-edb6-45b6-aa2a-f1c3c010abc3.PNG)

**Comment by chandkc** [comment]
@SumedhaBhosale References regarding limitation in torsions and how far we may go.
Does it becomes rigid, if we go more than 32 torsion? As of now, 32 torsions is the limit.

**Comment by SumedhaBhosale** [comment]
My mistake. Yes, 32 is the maximum for torsions and we cannot increase it. The option I tried is to **inactivate all torsions**. (-Z flag in prepare_ligand.py). By Default, all bonds are rotatable except amides. 
Or there is one more flag (-l) [_I haven't tried this_]  - where we can select which bonds to keep rotatable. 

We can provide these options as advanced parameters.

**Comment by chandkc** [comment]
Emailed @chandkc the Remote Directory and the summary and error files.

**Comment by chandkc** [comment]
```
`egrep FATAL STAT3B_model1_HTVS_446.dlg | sed "s/^.*FATAL//g"`

egrep "REMARK WARNING" l_HTVS_446.pdbqt 
```

**Comment by chandkc** [comment]
AutoDock sets the maximum number of torsions a ligand can have. When a ligand has more than this maximum number of torsions, you'll get "FATAL ERROR: PDBQT ERROR: too many torsions, maximum number of torsions is 32" error message. To run AutoDock with ligands that have too many torsions, limit the number of active torsions before making pdbqt files using Edit > Preferences > AutoDock > Ligand Preparation > Number of torsion: option. Set this to, say, 32 and remake ligand pdbqt file(s).
Source: https://pyrx.sourceforge.io/faq/87-faq

https://sunxiaoquan.wordpress.com/2015/02/02/increase-the-torsion-limit-in-autodock4-to-64/

**Comment by chandkc** [comment]
1. Upload is smi, csv
2. Upload is pdb/sdf

PDB, SDF is converted to SMILES before sending them to the server in CSV format.

`WARN=`egrep "REMARK WARNING" l_HTVS_446.pdbqt | wc -l``

If ${WARN} > 0 print {No. of torsions exceed the limt of 32.}
