### ISSUE TITLE
UserID not found when SDF used as ligand input file format 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/HTVS#32]
Hi,

UserID column is blank in case of SDF file format. Please check. Attaching screenshot. 

![HTVS_SDF](https://user-images.githubusercontent.com/105902516/186708114-607d4aee-e7b1-4788-ae05-34a5aa176fe9.png)

**Comment by sanvidat** [comment]
Bug fixed.

**Comment by SumedhaBhosale** [comment]
[coconut_Ayurveda.zip](https://github.com/chandkc/HTVS/files/9493441/coconut_Ayurveda.zip)

Input taken from - https://coconut.naturalproducts.net/

**Comment by chandkc** [comment]
Observations:

1. SDF is in some different format. The compound identifier is placed somewhere (not an usual place).
2. SDF is in 2D.

**Comment by chandkc** [comment]
Q. How many types of SDF format exists?

**Comment by chandkc** [comment]
1. SDF's recommended format (esp. compound name, compound id, molecule name) in the **i** button.
2. If any compound name is blank, prompt user.

**Comment by chandkc** [comment]
1. SDFs/PDBs are converted to SMILES.
2. For SDF, Compound name is recommended. (Refer Manual for detail)

**Comment by chandkc** [comment]
For Manual: @LobeliaG. Upload HTVS SDF format 
Placement of compound name, compound id, molecule name for SDF format.
-----------------------------------------------------------------------------
1. Two compounds in a file containing multiple compounds are separated by $$$$.
2. The first line after $$$$ is the placeholder for the compound name.
3. User can choose to identify the compound at this placeholder.
4. For only one compound, the first line is the compound name placeholder.

Unavailable entry in the Compound Name column of HTVS Summary (.csv) file denotes the compound name placeholder is blank.

**Comment by chandkc** [comment]
INFO: Compound name is not found in the input file(s).

**Comment by LobeliaG** [comment]
> ## For Manual: @LobeliaG. Upload HTVS SDF format
> Placement of compound name, compound id, molecule name for SDF format.
> 1. Two compounds in a file containing multiple compounds are separated by $$$$.
> 2. The first line after $$$$ is the placeholder for the compound name.
> 3. User can choose to identify the compound at this placeholder.
> 4. For only one compound, the first line is the compound name placeholder.
> 
> Unavailable entry in the Compound Name column of HTVS Summary (.csv) file denotes the compound name placeholder is blank.

Done.

**Comment by chandkc** [comment]
fixed.
