### ISSUE TITLE
PIPL01- 'Start Docking' non responsive

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/HTVS#33]
**machine- PIPL01
software- PRiNS_D_V_2_0_2_windows**
 After selection of combinations and host, when clicked on 'start docking', docking is not getting started. It is frozen as it is. Repeated 3 times.

![image](https://user-images.githubusercontent.com/111036161/186850228-892d6bce-cdae-4aff-ad36-3e547251454f.png)

**Comment by LobeliaG** [comment]
[Input_HTVS.zip](https://github.com/chandkc/HTVS/files/9430930/Input_HTVS.zip)

**Comment by sanvidat** [comment]
On ubuntu
![Run Docking Button](https://user-images.githubusercontent.com/105784499/186902226-eb518ff1-765b-4704-80b0-a616cfdccda2.png)

**Comment by SumedhaBhosale** [comment]
Hi,

Its still not working in exe dated 27 Aug. Please check !

**Comment by sanvidat** [comment]
Start Docking Button is working.
