### ISSUE TITLE
Error in docking through LS algorithm 

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/HTVS#37]
machine- PIPL01
windows version- TEST_V2_5

PDBQT files were not found for the protein-ligand combinations when docking was performed using LS algorithm. for the same files, docking was successful using LGA. I used LS as algorithm, and reduced the no of runs to 1 to reduce the time. Other parameters were kept as it is. Input ligand was .csv file.
![image](https://user-images.githubusercontent.com/111036161/189053048-ca6433c6-a37a-4a8e-a176-149c8852a2ac.png)

**Comment by chandkc** [comment]
User cannot set the lower bound of LS RUN to 1
Same applies to LGA settings.

We will set the lower bound to 1 for both LGA and LS.

@sanvidat Please implement.

**Comment by LobeliaG** [comment]
When **unbound model type is chosen as Extended**, and the algorithm is **LS**, **all of the combinations show error**. For Bound type only some of them do. However for **same inputs with LGA & extended** model type, docking takes place alright & same as 'Bound' type unbound model.
Number of runs were chosen more than 1 in each case. I am attaching the error files for both LS and LGA type produced from same input compound files.
[errorLGA.csv](https://github.com/chandkc/HTVS/files/9526611/errorLGA.csv)
[errorLS.csv](https://github.com/chandkc/HTVS/files/9526616/errorLS.csv)
input files- 
[Input_HTVS.zip](https://github.com/chandkc/HTVS/files/9526621/Input_HTVS.zip)
![LSextended](https://user-images.githubusercontent.com/111036161/189118632-d9039706-78b1-487d-ab0f-bf1eb7cae9fc.JPG)
![LS_para](https://user-images.githubusercontent.com/111036161/189118714-4328f750-b05f-4436-a340-51dfbee01b3d.JPG)

**Comment by chandkc** [comment]
Extended state has some issue. 
It not functioning, as expected.

Work in progress . . . . . .

**Comment by chandkc** [comment]
We will mute the extended option, for now.

Needs time to underestand and then to fix.

**Comment by LobeliaG** [comment]
Extended option seems to be working okay with LGA. As both Bound & Extended model options with LGA & Bound model in LS are generating same results. Only the extended model in LS does not.

**Comment by chandkc** [comment]
Thank you @LobeliaG for this report.

I did check.
There was something missing in the script of LS/Extended combination.
Will rectify and release.

`sed  '/ga_pop_size/a set_ga'` @sanvidat

**Comment by sanvidat** [comment]
fixed
