### ISSUE TITLE
Grid box not visible

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/HTVS#43]
Hi,

PRinS_Hackathon_Sep_Ubuntu_20_04_x64 
Ubuntu OS

something is wrong in Grid box 
![HTVS_GridBox](https://user-images.githubusercontent.com/105902516/190393891-6de5d044-f951-4c42-877f-51ec4b7ae5bd.png)

Same happened with Windows OS

**Comment by sanvidat** [comment]
Bug is fixed.
Source of this error is Statesave.
