### ISSUE TITLE
Error in entering GA run numbers

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/HTVS#44]
PIPL01
windows version- TEST_V2_9

No GA run numbers can be typed if it starts with 1, in user defined mode. We can type 20, but not 10.
![image](https://user-images.githubusercontent.com/111036161/190915537-68ec19dd-8c76-4191-8056-7c58cb636e36.png)

**Comment by sanvidat** [comment]
Bug fixed.
Some enhancement is needed.
