### ISSUE TITLE
LE with smiles

### ISSUE THREAD

**Issue by chandkc** [chandkc/HTVS#45]
Download option pdb/smiles format for the compounds that have good binding energies/score/no. of hydrogen bond.

We now get an complex for download, but if I want to have these smiles and use as an input in SyMoG we would need to have a list of smiles

**Comment by chandkc** [comment]
After
`rsync ${comb_name}"_LE.pdb" ${WD_DOCKING}/Summary/Lowest_Energy_Conformation`

`echo ${Smiles} > ${WD_DOCKING}/Summary/l_${comb_name}"_LE.smi`

**Comment by sanvidat** [comment]
Done

**Comment by sanvidat** [comment]
Implemented
