### ISSUE TITLE
Job status for a target show more than 100%

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/HTVS#48]
PIPL01
PRinS_V2_D_V_10 -windows version

The jobs are divided between local server & GPU-server of PIPL02. out of 8 targets, the jobs against more than 1 targets are showing it is completed more than 100%.
![image](https://user-images.githubusercontent.com/111036161/192750224-466232ea-cf11-4e13-88d9-49a72a9bc9fe.png)

Same percentage problem is seen in server table as well.
![image](https://user-images.githubusercontent.com/111036161/192750054-61f04eaf-6530-491d-b7e1-9786cf905d0b.png)

**Comment by sanvidat** [comment]
unable to reproduce the error
