### ISSUE TITLE
Space in sdf filenames

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/HTVS#55]
**PRinS_Ubuntu_20_86X64_2_0_0**

1. I gave sdf files which has space. The log shows **_given SDF format file was converted to Smile format_** but it is not getting converted.
2. User might save the filename with single/double quotes along with spaces. If the sdf input filenames have space or quotes then it is not proceeding further.

![HTVS1](https://user-images.githubusercontent.com/117424735/209616303-f21922a3-4cd1-4425-9ec3-5d3b1b10e3e6.png)
![HTVS](https://user-images.githubusercontent.com/117424735/209616306-4252bef3-10e3-45b4-b7b4-147bec624f55.png)

**Comment by MahimaKori** [comment]
Same issue is seen with pdb filenames that have spaces.

**Comment by mdaakhan** [comment]
Already Solved in the previous version
