### ISSUE TITLE
Deduction of Ligand molecules in HTVS 

### ISSUE THREAD

**Issue by Akhilesh-pres** [chandkc/HTVS#61]
Version : PRinS3_V_2_3_0_Windows
OS : Windows
System : PIPL01

Issue : The HTVS is automatically removing the ligand molecules after the submitting for docking. The submitted dataset had 501 ligands with one protein. It only took 414 jobs and rest of them were removed.

![image (2)](https://github.com/chandkc/HTVS/assets/173763601/44cdf834-c46f-4a2a-b9d4-b4bc8c3d1227)

**Comment by sougataprescience** [comment]
Thread issue preventing all ligand conversion to SMILES, causing job deductions.
