### ISSUE TITLE
Disabled next button 

### ISSUE THREAD

**Issue by ADHITHYA46** [chandkc/HTVS#62]
Version - PRinS3_V_2_1_0_Ubuntu_2020_64x
OS - Linux

After uploading the ligand files in PDB format to the ligand section, the log window shows that the PDB to SMILES conversion is completed, but unable to proceed further to the docking grid generation window (The "next" button remains disabled).

![image (3)](https://github.com/chandkc/HTVS/assets/137476221/fa3f57f4-6716-41cb-a6ce-b0a90937a6f7)

**Comment by sougataprescience** [comment]
The issue with the next button not getting enabled has been resolved. It was caused by a threading issue, which has now been fixed.
