### ISSUE TITLE
Issue reagrding HTVS job submission

### ISSUE THREAD

**Issue by ADHITHYA46** [chandkc/HTVS#63]
Version - PRinS3_V_2_1_0_Ubuntu_2020_64x
OS - Linux

After selecting the proteins and resources for HTVS job submission, the "Start Docking" icon is enabled but not functioning .
When clicking the icon, no file transfer to the resources is getting initiated and the docking process is stuck at this point. 
![htvs-2](https://github.com/chandkc/HTVS/assets/137476221/de94d27f-6f2b-4b94-b053-06d3db9c320b)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
