### ISSUE TITLE
Unresponsive docking job details window

### ISSUE THREAD

**Issue by ADHITHYA46** [chandkc/HTVS#64]
Version - PRinS3_V_2_1_0_Ubuntu_2020_64x
OS - Linux

After submitting the docking, the Docking Job Details window opened but appears to be stagnant, with no jobs being executed.

![image (4)](https://github.com/chandkc/HTVS/assets/137476221/ef81f93b-15fe-44f9-b708-8751b906c4cd)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
